"apiVersion": "kustomize.config.k8s.io/v1beta1"
"kind": "Kustomization"
"patchesStrategicMerge":
- |
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: system-upgrade-controller
    namespace: system-upgrade
  spec:
    template:
      spec:
        containers:
          - name: system-upgrade-controller
            volumeMounts:
              - name: ca-certificates
                mountPath: /var/lib/ca-certificates
        volumes:
          - name: ca-certificates
            hostPath:
              path: /var/lib/ca-certificates
              type: Directory
- "kured.yaml"
- "ccm.yaml"
"resources":
- "https://github.com/hetznercloud/hcloud-cloud-controller-manager/releases/download/v1.15.0/ccm-networks.yaml"
- "https://github.com/weaveworks/kured/releases/download/1.13.0/kured-1.13.0-dockerhub.yaml"
- "https://raw.githubusercontent.com/rancher/system-upgrade-controller/master/manifests/system-upgrade-controller.yaml"
- "hcloud-csi.yml"
- "nginx_ingress.yaml"
- "cilium.yaml"
- "cert_manager.yaml"
